export const LiquidLockerRedemptionAbi = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "fee", type: "uint256" },
    ],
    name: "Redeem",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "Exchange",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "capacity", type: "uint256" },
    ],
    name: "SetCapacity",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "enabled", type: "bool" },
    ],
    name: "SetEnabled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "recipient", type: "address" }],
    name: "SetLiquidLockerRecipient",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "recipient", type: "address" }],
    name: "SetYfiRecipient",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "management", type: "address" }],
    name: "PendingManagement",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "management", type: "address" }],
    name: "SetManagement",
    type: "event",
  },
  {
    inputs: [],
    name: "epoch",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fee",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_epoch", type: "uint256" }],
    name: "fee_at",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "_idx", type: "uint256" },
      { name: "_ll_amount", type: "uint256" },
    ],
    name: "redeem",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_idx", type: "uint256" },
      { name: "_yfi_amount", type: "uint256" },
    ],
    name: "exchange",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_token", type: "address" }],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_token", type: "address" },
      { name: "_amount", type: "uint256" },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_recipient", type: "address" }],
    name: "set_liquid_locker_recipient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_recipient", type: "address" }],
    name: "set_yfi_recipient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_idx", type: "uint256" },
      { name: "_capacity", type: "uint256" },
    ],
    name: "set_capacity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_idx", type: "uint256" },
      { name: "_enabled", type: "bool" },
    ],
    name: "set_enabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_management", type: "address" }],
    name: "set_management",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "accept_management",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "genesis",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "yfi",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lock",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "management",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pending_management",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "liquid_locker_recipient",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "yfi_recipient",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "tokens",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "scales",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "capacities",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "enabled",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "used",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "_genesis", type: "uint256" },
      { name: "_yfi", type: "address" },
      { name: "_lock", type: "uint256" },
      { name: "_tokens", type: "address[3]" },
      { name: "_scales", type: "uint256[3]" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;
