export const VotingEscrowRewardDistributorAbi = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "unlock_epoch", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "Migrate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "rewards", type: "uint256" },
    ],
    name: "Claim",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "caller", type: "address" },
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "rewards", type: "uint256" },
      { indexed: false, name: "bounty", type: "uint256" },
    ],
    name: "Reclaim",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "caller", type: "address" },
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "rewards", type: "uint256" },
      { indexed: false, name: "bounty", type: "uint256" },
    ],
    name: "Report",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "boost", type: "uint256" },
      { indexed: false, name: "unlock", type: "uint256" },
    ],
    name: "SetSnapshot",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "distributor", type: "address" }],
    name: "SetDistributor",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "claimer", type: "bool" },
    ],
    name: "SetClaimer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "expiration", type: "uint256" },
      { indexed: false, name: "bounty", type: "uint256" },
      { indexed: false, name: "recipient", type: "address" },
    ],
    name: "SetRewardExpiration",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "bounty", type: "uint256" },
      { indexed: false, name: "recipient", type: "address" },
    ],
    name: "SetReportBounty",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "management", type: "address" }],
    name: "PendingManagement",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "management", type: "address" }],
    name: "SetManagement",
    type: "event",
  },
  {
    inputs: [],
    name: "epoch",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_epoch", type: "uint256" }],
    name: "sync_total_weight",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_account", type: "address" }],
    name: "claim",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_account", type: "address" }],
    name: "reclaim",
    outputs: [
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_account", type: "address" }],
    name: "report",
    outputs: [
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sync_rewards",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_account", type: "address" }],
    name: "check_lock",
    outputs: [
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "_account", type: "address" },
      { name: "_amount", type: "uint256" },
      { name: "_boost", type: "uint256" },
      { name: "_unlock", type: "uint256" },
    ],
    name: "set_snapshot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_distributor", type: "address" }],
    name: "set_distributor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_account", type: "address" },
      { name: "_claimer", type: "bool" },
    ],
    name: "set_claimer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_expiration", type: "uint256" },
      { name: "_bounty", type: "uint256" },
      { name: "_recipient", type: "address" },
    ],
    name: "set_reward_expiration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_bounty", type: "uint256" },
      { name: "_recipient", type: "address" },
    ],
    name: "set_report_bounty",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_management", type: "address" }],
    name: "set_management",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "accept_management",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "genesis",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "veyfi",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "management",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pending_management",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "distributor",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "address" }],
    name: "claimers",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reward_expiration",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reclaim_bounty",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reclaim_recipient",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "report_bounty",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "report_recipient",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "last_epoch",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reward_epoch",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "total_weights",
    outputs: [
      {
        components: [
          { name: "weight", type: "uint256" },
          { name: "slope", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "unlocks",
    outputs: [
      {
        components: [
          { name: "amount", type: "uint256" },
          { name: "slope_change", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "rewards",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "address" }],
    name: "locks",
    outputs: [
      {
        components: [
          { name: "amount", type: "uint256" },
          { name: "boost_epochs", type: "uint256" },
          { name: "unlock_time", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "address" }],
    name: "last_claimed",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "_distributor", type: "address" },
      { name: "_token", type: "address" },
      { name: "_veyfi", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;
