export const YbcElectionAbi = [
  {
    inputs: [],
    name: "addition_threshold",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "expulsion_threshold",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "num_proposals",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "proposals",
    outputs: [
      { name: "account", type: "address" },
      { name: "proposer", type: "address" },
      { name: "epoch", type: "uint256" },
      { name: "addition", type: "bool" },
      { name: "threshold", type: "uint256" },
      { name: "votes", type: "uint256" },
      { name: "yea", type: "uint256" },
      { name: "retracted", type: "bool" },
      { name: "executed", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_account", type: "address" }],
    name: "propose_addition",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_account", type: "address" }],
    name: "propose_expulsion",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_idx", type: "uint256" }],
    name: "retract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_account", type: "address" },
      { name: "_idx", type: "uint256" },
    ],
    name: "voted",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_idx", type: "uint256" }],
    name: "vote_yea",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_idx", type: "uint256" }],
    name: "vote_nay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_idx", type: "uint256" }],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_idx", type: "uint256" }],
    name: "status",
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
